application: ulyssesjason
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /img
  static_dir: img

- url: /.*
  script: url.rule

libraries:
- name: jinja2
  version: latest

- name: PIL
  version: "1.1.7"